name: Django App CI/CD Pipeline with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # or any Python version you need

      # Step 3: Install dependencies for Django and testing
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # If you're using pytest for testing

      # Step 4: Run tests
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      # Step 5: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 6: Build the Docker image for the Django app
      - name: Build Docker image
        run: |
          docker build -t your-image-name .
          
      # Step 7: Log in to Docker Hub (if you're deploying to Docker Hub)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 8: Push the Docker image to Docker Hub (Optional step)
      - name: Push Docker image
        run: |
          docker push your-image-name

      # Step 9: Deploy (You can use any deployment method)
      # Example: Deploy to AWS Elastic Beanstalk (adjust as per your deployment method)
      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          region: 'us-east-1' # Specify your region
          application_name: 'your-application-name'
          environment_name: 'your-environment-name'
          version_label: 'v${{ github.sha }}'
          bucket_name: 'your-s3-bucket-name'

